<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Форма /ru/OrderStick',
	'heading' => 'Отправка новой формы',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_reCAPTCHA2_private_key' => 'Недействительный закрытый ключ reCAPTCHA 2.0.',
		'invalid_reCAPTCHA2_server_response' => 'Недействительный ответ сервера reCAPTCHA 2.0.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => 'oneblending@gmail.com',
		'to' => 'oneblending@gmail.com'
	),
	'fields' => array(
		'custom_U10055' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Укажите требуемое количество плееров',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Укажите требуемое количество плееров\' не может быть пустым.'
			)
		),
		'Email' => array(
			'order' => 6,
			'type' => 'email',
			'label' => 'Ваш Email',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Ваш Email\' не может быть пустым.',
				'format' => 'Поле \'Ваш Email\' содержит недействительное сообщение эл. почты.'
			)
		),
		'custom_U10060' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Сообщение',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U10050' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Компания',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Компания\' не может быть пустым.'
			)
		),
		'custom_U10064' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Город',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Город\' не может быть пустым.'
			)
		),
		'custom_U10037' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'ИНН',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'ИНН\' не может быть пустым.'
			)
		),
		'custom_U10041' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Телефон для связи',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U10068' => array(
			'order' => 9,
			'type' => 'checkbox',
			'label' => 'Принимаю условия лицензионного соглашения >',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Принимаю условия лицензионного соглашения >\' не может быть пустым.'
			)
		),
		'custom_U10045' => array(
			'order' => 10,
			'type' => 'checkbox',
			'label' => 'Согласен на обработку контактной информации >',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Согласен на обработку контактной информации >\' не может быть пустым.'
			)
		),
		'custom_U10583' => array(
			'order' => 1,
			'type' => 'radiogroup',
			'label' => 'Группа переключателей',
			'required' => true,
			'optionItems' => array(
				'OneBlending  Intel® Compute Stick®',
				'Пользовательский текст:'
			),
			'errors' => array(
				'required' => 'Поле \'Группа переключателей\' не может быть пустым.',
				'format' => 'Недопустимое значение поля \"Группа переключателей\".'
			)
		)
	)
);

process_form($form);
?>
