<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Форма Без имени 12',
	'heading' => 'Отправка новой формы',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_reCAPTCHA2_private_key' => 'Недействительный закрытый ключ reCAPTCHA 2.0.',
		'invalid_reCAPTCHA2_server_response' => 'Недействительный ответ сервера reCAPTCHA 2.0.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => 'bw@mcdis.ru',
		'to' => 'bw@mcdis.ru'
	),
	'fields' => array(
		'Email' => array(
			'order' => 4,
			'type' => 'email',
			'label' => 'Ваш Email',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Ваш Email\' не может быть пустым.',
				'format' => 'Поле \'Ваш Email\' содержит недействительное сообщение эл. почты.'
			)
		),
		'custom_U18715' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Вид деятельности компании',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Вид деятельности компании\' не может быть пустым.'
			)
		),
		'custom_U18694' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Компания',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Компания\' не может быть пустым.'
			)
		),
		'custom_U18710' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Город',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Город\' не может быть пустым.'
			)
		),
		'custom_U18706' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Телефон для связи',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Телефон для связи\' не может быть пустым.'
			)
		),
		'custom_U18702' => array(
			'order' => 8,
			'type' => 'checkbox',
			'label' => 'Согласен на обработку контактной информации >',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Согласен на обработку контактной информации >\' не может быть пустым.'
			)
		),
		'custom_U18720' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Веб-сайт',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U18698' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Имя',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Имя\' не может быть пустым.'
			)
		)
	)
);

process_form($form);
?>
